site: Sumit Sharma
title: Sumit Sharma - A Product Designer for Design Systems
greetings: Hi 👋
description: >-
  Hello, I am Sumit Sharma. A Product designer for Design Systems currently working at Jupiter Money
lang: en
image: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1669559669/Portfolio/og_zr3bcq.webp
timezone: Asia/Kolkata
repo: https://github.com/sumit-sharrma # site repo [optional]
data-theme: light # default theme "dark" | "light"
discus-identifier: webthme
default-thumb: https://res.cloudinary.com/notee/image/upload/v1640412257/notes/default-thumb.webp

author:
  name: Sumit Sharma
  url: https://designerwhocode.com/
  bio: Sumit Sharma - A Product Designer for Design Systems
  avatar: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1667323476/sumit_kkvcak.jpg
  username: sumit_sharrma # general username
  github: sumit-sharrma # github username
  twitter: sumit_sharrma # twitter username
  email: sumitsp04@gmail.com # email adress

twitter:
  username: sumit_sharrma
  card: summary_large_image
  description: Hello, I am Sumit Sharma. A Product designer for Design Systems currently working at Jupiter Money

# Font Settings
# googlewebfonts: Inter:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap

# URL settings {Staging}
# url: "https://sumit-sharrma.github.io" # Domain Name of host. [username].github.io for github pages
# baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
# permalink: pretty

# URL settings {Prod}
url: "https://www.designerwhocode.com" # Domain Name of host. [username].github.io for github pages
# baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

# webp images
# Europa 2.0
europa:
  bg: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454344/Portfolio/europa-bg_b642sb.webp
  audit-1: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668452183/Portfolio/audit-1_iosrea.webp
  audit-2: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668453201/Portfolio/audit-2_ltphog.webp
  colors: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454344/Portfolio/colors_fyii0y.webp
  color-palette: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668453200/Portfolio/color-palette_ahvs03.webp
  typography: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454343/Portfolio/typography_oumigr.webp
  spacing: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454343/Portfolio/spacing_tgcyyb.webp
  icons: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454343/Portfolio/icons_wwbhgc.webp
  button: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454939/Portfolio/button_u737fq.webp
  form: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454940/Portfolio/form_odo7fq.webp
  other-comp: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454940/Portfolio/other-comp_vwtabw.webp
  documentation: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1668454940/Portfolio/documentation_dvo1zg.webp


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

google_analytics: "G-474P1GNEM9"
google_tag_manager: "GTM-54W357T"

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: style
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug/
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: https://res.cloudinary.com/dcx5qfzvy/image/upload/v1669559669/Portfolio/og_zr3bcq.webp
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

relative_links:
  enabled: true
  collections: false
